Repository withfoodmate/backend, pull requests merged in 2023-10, with the labels that each got.

#2 랭킹 API - 좋아요 랭킹 기능 추가
  src/main/java/com/foodmate/backend/controller/RankingController.java
  src/main/java/com/foodmate/backend/dto/RankingDto.java
  src/main/java/com/foodmate/backend/entity/Member.java
  src/main/java/com/foodmate/backend/repository/MemberRepository.java
  src/main/java/com/foodmate/backend/service/RankingService.java
  src/main/java/com/foodmate/backend/service/impl/RankingServiceImpl.java
Labels: enhancement

#3 랭킹 API - 모임왕 랭킹 기능 추가
  build.gradle
  src/main/java/com/foodmate/backend/BackendApplication.java
  src/main/java/com/foodmate/backend/controller/RankingController.java
  src/main/java/com/foodmate/backend/dto/RankingDto.java
  src/main/java/com/foodmate/backend/entity/Food.java
  src/main/java/com/foodmate/backend/entity/FoodGroup.java
  src/main/java/com/foodmate/backend/repository/MemberRepository.java
  src/main/java/com/foodmate/backend/service/RankingService.java
  src/main/java/com/foodmate/backend/service/impl/RankingServiceImpl.java
Labels: enhancement

#4 카카오 로그인 API - 로그인 기능 작동 확인
  src/main/java/com/foodmate/backend/entity/Member.java
  src/main/java/com/foodmate/backend/repository/MemberRepository.java
  src/main/java/com/foodmate/backend/security/service/KakaoOAuth2MemberService.java
Labels: enhancement

#8 Feature/profile-image 사용자 프로필 이미지 변경 기능 구현 완료
  src/main/java/com/foodmate/backend/configure/S3Config.java
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/entity/Member.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/main/java/com/foodmate/backend/service/impl/MemberServiceImpl.java
  src/main/java/com/foodmate/backend/util/FileRandomNaming.java
  src/main/java/com/foodmate/backend/util/S3Deleter.java
  src/main/java/com/foodmate/backend/util/S3Uploader.java
Labels: enhancement

#13 카카오 로그인 API - 회원가입 기능 추가
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/enums/MemberLoginType.java
  src/main/java/com/foodmate/backend/enums/MemberRole.java
  src/main/java/com/foodmate/backend/exception/AuthException.java
  src/main/java/com/foodmate/backend/security/config/SecurityConfig.java
  src/main/java/com/foodmate/backend/security/config/SecurityOAuthConfig.java
  src/main/java/com/foodmate/backend/security/filter/handler/ApiAccessDeniedHandler.java
  src/main/java/com/foodmate/backend/security/filter/handler/ApiAuthenticationEntryPoint.java
  src/main/java/com/foodmate/backend/security/filter/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/foodmate/backend/security/filter/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/foodmate/backend/security/service/KakaoOAuth2MemberService.java
Labels: enhancement

#15 JWT 토큰 발급 기능 추가
  src/main/java/com/foodmate/backend/entity/Member.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/repository/MemberRepository.java
  src/main/java/com/foodmate/backend/security/config/SecurityConfig.java
  src/main/java/com/foodmate/backend/security/filter/ExceptionHandlerFilter.java
  src/main/java/com/foodmate/backend/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/foodmate/backend/security/filter/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/foodmate/backend/security/service/JwtTokenProvider.java
  src/main/java/com/foodmate/backend/util/PasswordUtil.java
Labels: enhancement

#16 그룹 API - 모임 생성 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/dto/GroupDto.java
  src/main/java/com/foodmate/backend/entity/ChatRoom.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/exception/FoodException.java
  src/main/java/com/foodmate/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/foodmate/backend/exception/GroupException.java
  src/main/java/com/foodmate/backend/repository/ChatRoomRepository.java
  src/main/java/com/foodmate/backend/repository/FoodRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#20 Feature/email duplicate check 이메일 중복체크 기능 추가
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/dto/MemberDto.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/main/java/com/foodmate/backend/service/impl/MemberServiceImpl.java
Labels: enhancement

#21 그룹 API - 모임 상세 조회 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/dto/GroupDto.java
  src/main/java/com/foodmate/backend/entity/Enrollment.java
  src/main/java/com/foodmate/backend/enums/EnrollmentStatus.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/exception/ChatException.java
  src/main/java/com/foodmate/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/foodmate/backend/repository/ChatRoomRepository.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#24 그룹 API - 모임 수정 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#25 그룹 API - 모임 삭제 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/repository/ChatRoomRepository.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#29 Feature/nickname duplicate check 닉네임 중복 검사 기능 추가
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/dto/MemberDto.java
  src/main/java/com/foodmate/backend/repository/MemberRepository.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/main/java/com/foodmate/backend/service/impl/MemberServiceImpl.java
Labels: enhancement

#30 그룹 API - 모임 참가 신청 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/exception/EnrollmentException.java
  src/main/java/com/foodmate/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#31 Feature/logout 로그아웃 기능 추가
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/security/config/SecurityConfig.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/main/java/com/foodmate/backend/service/impl/MemberServiceImpl.java
Labels: enhancement

#32 Feature/other user info 다른 유저정보 보기 기능 추가
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/main/java/com/foodmate/backend/service/impl/MemberServiceImpl.java
Labels: enhancement

#33 그룹 API - 댓글 작성 & 대댓글 작성 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/dto/CommentDto.java
  src/main/java/com/foodmate/backend/dto/ReplyDto.java
  src/main/java/com/foodmate/backend/entity/Comment.java
  src/main/java/com/foodmate/backend/entity/Reply.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/exception/CommentException.java
  src/main/java/com/foodmate/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#34 일반 회원가입 기능 추가
  src/main/java/com/foodmate/backend/component/MailComponents.java
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/dto/MemberDto.java
  src/main/java/com/foodmate/backend/entity/Member.java
  src/main/java/com/foodmate/backend/entity/Preference.java
  src/main/java/com/foodmate/backend/enums/EmailContents.java
  src/main/java/com/foodmate/backend/repository/MemberRepository.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/main/java/com/foodmate/backend/service/impl/MemberServiceImpl.java
Labels: enhancement

#35 그룹 API - 댓글 수정 & 대댓글 수정 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/foodmate/backend/exception/ReplyException.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#36 그룹 API - 댓글 삭제 & 대댓글 삭제 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/repository/ReplyRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#37 Feature/likes 좋아요 누름 기능 추가
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/entity/Likes.java
  src/main/java/com/foodmate/backend/repository/LikesRepository.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/main/java/com/foodmate/backend/service/impl/MemberServiceImpl.java
Labels: enhancement

#38 그룹 API - 댓글 대댓글 전체 조회 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/dto/CommentDto.java
  src/main/java/com/foodmate/backend/dto/ReplyDto.java
  src/main/java/com/foodmate/backend/repository/CommentRepository.java
  src/main/java/com/foodmate/backend/repository/ReplyRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#41 회원 API - 일반 로그인 기능 추가
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/security/dto/JwtTokenDto.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/main/java/com/foodmate/backend/service/impl/MemberServiceImpl.java
Labels: enhancement

#42 Feature/password change 패스워드 변경 기능 추가
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/dto/MemberDto.java
  src/main/java/com/foodmate/backend/entity/Member.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/main/java/com/foodmate/backend/service/impl/MemberServiceImpl.java
Labels: enhancement

#50 그룹 API - 검색 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/dto/SearchedGroupDto.java
  src/main/java/com/foodmate/backend/repository/FoodGroupRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#58 그룹 API - 오늘의 모임 조회 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/repository/FoodGroupRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#59 그룹 API - 전체 모임 조회 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/repository/FoodGroupRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#60 모인 신청 API - 내 신청 목록 조회 기능 추가
  src/main/java/com/foodmate/backend/controller/EnrollmentController.java
  src/main/java/com/foodmate/backend/dto/EnrollmentDto.java
  src/main/java/com/foodmate/backend/enums/EnrollmentStatus.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/service/EnrollmentService.java
  src/main/java/com/foodmate/backend/service/impl/EnrollmentServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#63 신청 API - 본인이 생성한 모든 모임 요청 조회 기능 추가
  src/main/java/com/foodmate/backend/controller/EnrollmentController.java
  src/main/java/com/foodmate/backend/dto/EnrollmentDto.java
  src/main/java/com/foodmate/backend/entity/Enrollment.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/service/EnrollmentService.java
  src/main/java/com/foodmate/backend/service/impl/EnrollmentServiceImpl.java
Labels: enhancement

#65 그룹 API - 내 근처 모임(거리순) 조회 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/repository/FoodGroupRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#66 신청 API - 모임 요청 수락 or 거절
  src/main/java/com/foodmate/backend/controller/EnrollmentController.java
  src/main/java/com/foodmate/backend/entity/Enrollment.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/service/EnrollmentService.java
  src/main/java/com/foodmate/backend/service/impl/EnrollmentServiceImpl.java
Labels: enhancement

#67 그룹 API - 날짜별 조회 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/repository/FoodGroupRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#68 그룹 API - 메뉴별 조회 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/repository/FoodGroupRepository.java
  src/main/java/com/foodmate/backend/repository/FoodRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
Labels: enhancement

#69 신청 API - 나의 신청 취소 기능
  src/main/java/com/foodmate/backend/controller/EnrollmentController.java
  src/main/java/com/foodmate/backend/entity/Enrollment.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/service/EnrollmentService.java
  src/main/java/com/foodmate/backend/service/impl/EnrollmentServiceImpl.java
Labels: enhancement

#71 그룹 API - 내 근처 모임(거리순) 조회 기능 쿼리 수정
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/repository/FoodGroupRepository.java
Labels: enhancement

#73 랭킹 API & 그룹 API 리팩토링
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/dto/GroupDto.java
  src/main/java/com/foodmate/backend/dto/SearchedGroupDto.java
  src/main/java/com/foodmate/backend/entity/FoodGroup.java
  src/main/java/com/foodmate/backend/enums/GroupStatus.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/repository/FoodGroupRepository.java
  src/main/java/com/foodmate/backend/repository/FoodRepository.java
  src/main/java/com/foodmate/backend/repository/MemberRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/RankingService.java
  src/main/java/com/foodmate/backend/service/impl/GroupServiceImpl.java
  src/main/java/com/foodmate/backend/service/impl/RankingServiceImpl.java
Labels: refactor

#74 Refactor/enrollment 모임신청 리팩토링
  src/main/java/com/foodmate/backend/controller/EnrollmentController.java
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/dto/EnrollmentDto.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/service/EnrollmentService.java
  src/main/java/com/foodmate/backend/service/S3Deleter.java
  src/main/java/com/foodmate/backend/service/S3Uploader.java
  src/main/java/com/foodmate/backend/service/impl/MemberServiceImpl.java
  src/test/java/com/foodmate/backend/controller/EnrollmentControllerTest.java
Labels: enhancement

#75 그룹 API - 로그인한 사용자가 참여한 모임 조회 기능 추가
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/dto/GroupDto.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
Labels: enhancement

#78 그룹 API 리팩토링 & CORS 설정 클래스 추가
  src/main/java/com/foodmate/backend/configure/WebConfig.java
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/service/GroupService.java
Labels: refactor

#81 채팅 API - 채팅 리스트 및 채팅방 정보 가져오기 기능
  src/main/java/com/foodmate/backend/controller/ChatRoomController.java
  src/main/java/com/foodmate/backend/dto/ChatDto.java
  src/main/java/com/foodmate/backend/entity/ChatMember.java
  src/main/java/com/foodmate/backend/entity/ChatMessage.java
  src/main/java/com/foodmate/backend/entity/ChatRoom.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/repository/ChatMemberRepository.java
  src/main/java/com/foodmate/backend/repository/ChatMessageRepository.java
  src/main/java/com/foodmate/backend/repository/ChatRoomRepository.java
  src/main/java/com/foodmate/backend/service/ChatRoomService.java
Labels: enhancement

#84 그룹 API - 모임 생성 테스트 코드 추가
  src/main/java/com/foodmate/backend/dto/GroupDto.java
  src/main/java/com/foodmate/backend/entity/Food.java
  src/test/java/com/foodmate/backend/service/GroupServiceTest.java
Labels: test

#86 그룹 API - 특정 모임 상세 조회 테스트 코드 추가
  src/main/java/com/foodmate/backend/entity/ChatRoom.java
  src/test/java/com/foodmate/backend/service/GroupServiceTest.java
Labels: test

#87 랭킹 API & 그룹 API 리팩토링 2차
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/controller/RankingController.java
  src/main/java/com/foodmate/backend/repository/FoodGroupRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/main/java/com/foodmate/backend/service/RankingService.java
Labels: refactor

#88 Security 관련 리팩토링
  src/main/java/com/foodmate/backend/security/config/SecurityConfig.java
  src/main/java/com/foodmate/backend/security/filter/ExceptionHandlerFilter.java
  src/main/java/com/foodmate/backend/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/foodmate/backend/security/filter/handler/ApiAccessDeniedHandler.java
  src/main/java/com/foodmate/backend/security/filter/handler/ApiAuthenticationEntryPoint.java
Labels: refactor

#90 Refactor/enrollment 모임신청 리팩토링 2차
  src/main/java/com/foodmate/backend/controller/EnrollmentController.java
  src/main/java/com/foodmate/backend/dto/EnrollmentDto.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/service/EnrollmentService.java
Labels: refactor

#91 그룹 API - 특정 모임 수정 테스트 코드 추가
  src/test/java/com/foodmate/backend/service/GroupServiceTest.java
Labels: test

#92 유저 API - 2차 리팩토링 및 빠진 기능 추가
  build.gradle
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/dto/MemberDto.java
  src/main/java/com/foodmate/backend/entity/Member.java
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/enums/MessageType.java
  src/main/java/com/foodmate/backend/exception/FileException.java
  src/main/java/com/foodmate/backend/exception/GlobalExceptionHandler.java
  src/main/java/com/foodmate/backend/security/dto/JwtTokenDto.java
  src/main/java/com/foodmate/backend/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/foodmate/backend/security/service/JwtTokenProvider.java
  src/main/java/com/foodmate/backend/security/service/KakaoOAuth2MemberService.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/main/java/com/foodmate/backend/service/S3Deleter.java
  src/main/java/com/foodmate/backend/util/FileRandomNaming.java
  src/main/java/com/foodmate/backend/util/PasswordUtil.java
  src/main/java/com/foodmate/backend/util/RandomStringMaker.java
  src/test/java/com/foodmate/backend/BackendApplicationTests.java
  src/test/java/com/foodmate/backend/controller/EnrollmentControllerTest.java
Labels: enhancement, refactor

#93 그룹 API - 특정 모임 삭제 테스트 코드 추가
  src/test/java/com/foodmate/backend/service/GroupServiceTest.java
Labels: test

#96 그룹 API - 특정 모임 신청 테스트 코드 추가
  src/test/java/com/foodmate/backend/service/GroupServiceTest.java
Labels: test

#97 그룹 API - 댓글 작성 & 대댓글 작성 테스트 코드 추가
  src/main/java/com/foodmate/backend/dto/CommentDto.java
  src/main/java/com/foodmate/backend/dto/ReplyDto.java
  src/test/java/com/foodmate/backend/service/GroupServiceTest.java
Labels: test

#98 유저 API - 에러메세지 변경
  src/main/java/com/foodmate/backend/enums/Error.java
Labels: refactor

#100 그룹 API 리팩토링 ( DTO , 내 근처 모임 API 관련 )
  src/main/java/com/foodmate/backend/controller/GroupController.java
  src/main/java/com/foodmate/backend/dto/CommentDto.java
  src/main/java/com/foodmate/backend/dto/GroupDto.java
  src/main/java/com/foodmate/backend/dto/NearbyGroupDto.java
  src/main/java/com/foodmate/backend/dto/ReplyDto.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/repository/FoodGroupRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
Labels: refactor

#101 신청 API - 본인이 생성한 모든 모임(processed)의 요청 조회 성공 테스트 케이스
  src/test/java/com/foodmate/backend/service/EnrollmentServiceTest.java
Labels: test

#103 유저 API - 이메일, 닉네임 중복확인 부분 어노테이션 수정
  src/main/java/com/foodmate/backend/controller/MemberController.java
Labels: refactor

#99 유저 API - 내 정보 가져오기 테스트 작성
  src/test/java/com/foodmate/backend/service/MemberServiceTest.java
Labels: test

#102 그룹 API - 댓글 수정 & 대댓글 수정 테스트 코드 추가
  src/test/java/com/foodmate/backend/service/GroupServiceTest.java
Labels: test

#104 그룹 API - 댓글 삭제 & 대댓글 삭제 테스트 코드 추가
  src/test/java/com/foodmate/backend/service/GroupServiceTest.java
Labels: test

#107 채팅 API - 구독/구독취소 이벤트 발생시 ChatMember 추가/삭제
  src/main/java/com/foodmate/backend/component/WebSocketEventListener.java
  src/main/java/com/foodmate/backend/entity/ChatMember.java
  src/main/java/com/foodmate/backend/repository/ChatMemberRepository.java
  src/main/java/com/foodmate/backend/service/ChatMessageService.java
  src/main/java/com/foodmate/backend/service/GroupService.java
Labels: enhancement

#108 채팅 API - ChatMember 중복 생성 방지 코드 추가
  src/main/java/com/foodmate/backend/entity/ChatMember.java
  src/main/java/com/foodmate/backend/repository/ChatMemberRepository.java
  src/main/java/com/foodmate/backend/service/ChatMessageService.java
  src/test/java/com/foodmate/backend/service/GroupServiceTest.java
Labels: enhancement

#109 채팅 API - 채팅리스트 null분기처리
  src/main/java/com/foodmate/backend/dto/ChatDto.java
  src/main/java/com/foodmate/backend/service/ChatRoomService.java
Labels: refactor

#110 스웨거 적용
  build.gradle
  src/main/java/com/foodmate/backend/configure/SwaggerConfig.java
  src/main/resources/application.yml
Labels: enhancement

#111 신청 API - API 내 신청 목록 API 기능 변경 및 내가 모집중인 그룹 신청 전체 조회 추가
  src/main/java/com/foodmate/backend/controller/EnrollmentController.java
  src/main/java/com/foodmate/backend/dto/EnrollmentDto.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/service/EnrollmentService.java
Labels: enhancement, refactor

#112 유저 API - 좋아요 누르기 취소
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/dto/MemberDto.java
  src/main/java/com/foodmate/backend/service/MemberService.java
Labels: refactor

#113 유저API - 유저 좋아요 리턴 값 변경
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/service/MemberService.java
Labels: refactor

#115 유저 API - 다른 유저의 정보 찾기 필요한 데이터 추가
  src/main/java/com/foodmate/backend/controller/MemberController.java
  src/main/java/com/foodmate/backend/dto/MemberDto.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/test/java/com/foodmate/backend/controller/EnrollmentControllerTest.java
  src/test/java/com/foodmate/backend/service/MemberServiceTest.java
Labels: refactor

#114 그룹 API - 테스트 코드 추가
  src/test/java/com/foodmate/backend/service/GroupServiceTest.java
Labels: test

#117 신청 API - 기능 일부 수정
  src/main/java/com/foodmate/backend/entity/Enrollment.java
  src/main/java/com/foodmate/backend/entity/FoodGroup.java
  src/main/java/com/foodmate/backend/service/EnrollmentService.java
  src/test/java/com/foodmate/backend/service/EnrollmentServiceTest.java
Labels: refactor

#118 유저API - 에러 수정 및 코드 리팩토링
  src/main/java/com/foodmate/backend/service/MemberService.java
Labels: bug, refactor

#120 신청 API - 기존 신청리스트 수정 및 과거 신청리스트 기능 추가
  src/main/java/com/foodmate/backend/controller/EnrollmentController.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/service/EnrollmentService.java
Labels: enhancement, refactor

#121 신청 API - url 변경
  src/main/java/com/foodmate/backend/controller/EnrollmentController.java
Labels: refactor

#122 스케쥴러 생성 - 모임완료 처리 및 채팅방 삭제
  src/main/java/com/foodmate/backend/BackendApplication.java
  src/main/java/com/foodmate/backend/component/Scheduler.java
  src/main/java/com/foodmate/backend/repository/ChatMemberRepository.java
  src/main/java/com/foodmate/backend/repository/ChatMessageRepository.java
  src/main/java/com/foodmate/backend/repository/EnrollmentRepository.java
  src/main/java/com/foodmate/backend/repository/FoodGroupRepository.java
  src/main/java/com/foodmate/backend/service/GroupService.java
  src/test/java/com/foodmate/backend/service/GroupServiceTest.java
Labels: enhancement

#124 랭킹 API - 테스트 코드
  src/test/java/com/foodmate/backend/service/RankingServiceTest.java
Labels: test

#125 유저 API - 회원탈퇴 리팩토링 및 검증 추가
  src/main/java/com/foodmate/backend/enums/Error.java
  src/main/java/com/foodmate/backend/service/MemberService.java
  src/test/java/com/foodmate/backend/service/MemberServiceTest.java
Labels: refactor, test
